#!/usr/bin/env python3
"""One-time font setup: downloads latin-subset woff2 files from the Google
Fonts CSS API into docs/assets/fonts/ and writes docs/assets/fonts.css with
relative-path @font-face rules. Fonts are committed; re-run only if missing.
"""

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "docs" / "assets" / "fonts"
FONTS_CSS = ROOT / "docs" / "assets" / "fonts.css"

# Desktop UA so the API serves woff2 sources.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

FAMILIES = [
    ("Fraunces", "Fraunces:wght@400;600;900"),
    ("IBM Plex Sans", "IBM+Plex+Sans:wght@400;500;600"),
    ("IBM Plex Mono", "IBM+Plex+Mono:wght@400;500"),
]

FACE_RE = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*"
    r"@font-face\s*\{(?P<body>.*?)\}", re.S)
PROP_RE = re.compile(r"(?P<key>[\w-]+)\s*:\s*(?P<val>[^;]+);")
URL_RE = re.compile(r"url\((?P<url>https://[^)]+\.woff2)\)")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def slug(family):
    return family.lower().replace(" ", "-")


def main():
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    rules = []
    downloaded = 0
    # Variable families serve one woff2 for every weight; download it once.
    url_to_file = {}

    for family, spec in FAMILIES:
        css_url = ("https://fonts.googleapis.com/css2?family=%s&display=swap"
                   % spec)
        css = fetch(css_url).decode("utf-8")
        found = 0

        for m in FACE_RE.finditer(css):
            if m.group("subset") != "latin":
                continue
            props = dict((p.group("key"), p.group("val").strip())
                         for p in PROP_RE.finditer(m.group("body")))
            um = URL_RE.search(props.get("src", ""))
            if not um:
                continue
            weight = props.get("font-weight", "400")
            style = props.get("font-style", "normal")
            url = um.group("url")
            if url in url_to_file:
                fname = url_to_file[url]
            else:
                fname = "%s-%s%s.woff2" % (
                    slug(family), weight,
                    "" if style == "normal" else "-" + style)
                dest = FONTS_DIR / fname
                if not dest.exists():
                    dest.write_bytes(fetch(url))
                    downloaded += 1
                url_to_file[url] = fname
            rules.append(
                "@font-face {\n"
                "  font-family: '%s';\n"
                "  font-style: %s;\n"
                "  font-weight: %s;\n"
                "  font-display: swap;\n"
                "  src: url(fonts/%s) format('woff2');\n"
                "  unicode-range: %s;\n"
                "}\n" % (family, style, weight, fname,
                         props.get("unicode-range", "U+0000-00FF")))
            found += 1

        if not found:
            print("WARNING: no latin faces found for %s" % family)

    FONTS_CSS.write_text(
        "/* Generated by tools/build_fonts.py. Self-hosted latin subsets. */\n\n"
        + "\n".join(rules), encoding="utf-8")
    print("Wrote %s (%d faces, %d files downloaded)"
          % (FONTS_CSS.relative_to(ROOT), len(rules), downloaded))


if __name__ == "__main__":
    sys.exit(main())
